import React,{useState} from 'react'

function DiseasesInfo() {
    const [ info, setInfo ] = useState([
        {
            "id": 100,
            "name": "Malaria - WHO",
            "data_updated_at": "April 2016",
            "facts": [
            "Malaria is a life-threatening disease caused by parasites that are transmitted to people through the bites of infected female Anopheles mosquitoes.",
            "In 2015, 95 countries and territories had ongoing malaria transmission,",
            "About 3.2 billion people – almost half of the world’s population – are at risk of malaria.",
            "Malaria is preventable and curable, and increased efforts are dramatically reducing the malaria burden in many places.",
            "Between 2000 and 2015, malaria incidence among populations at risk (the rate of new cases) fell by 37% globally. In that same period, malaria death rates among populations at risk fell by 60% globally among all age groups, and by 65% among children under 5.",
            "Sub-Saharan Africa carries a disproportionately high share of the global malaria burden. In 2015, the region was home to 88% of malaria cases and 90% of malaria deaths."
            ],
            "symptoms": "\n  \t\t\n  \t\tMalaria is an acute febrile illness. In a non-immune individual, symptoms appear 7 days or more (usually 10–15 days) after the infective mosquito bite. The first symptoms – fever, headache, chills and vomiting – may be mild and difficult to recognize as malaria. If not treated within 24 hours, P. falciparum malaria can progress to severe illness, often leading to death. \n  \t\t\n  \t\tChildren with severe malaria frequently develop one or more of the following symptoms: severe anaemia, respiratory distress in relation to metabolic acidosis, or cerebral malaria. In adults, multi-organ involvement is also frequent. In malaria endemic areas, people may develop partial immunity, allowing asymptomatic infections to occur.",
            "transmission": "\n  \t\t\n  \t\tIn most cases, malaria is transmitted through the bites of female Anopheles mosquitoes. There are more than 400 different species of Anopheles mosquito; around 30 are malaria vectors of major importance. All of the important vector species bite between dusk and dawn. The intensity of transmission depends on factors related to the parasite, the vector, the human host, and the environment.\n  \t\t\n  \t\tAnopheles mosquitoes lay their eggs in water, which hatch into larvae, eventually emerging as adult mosquitoes. The female mosquitoes seek a blood meal to nurture their eggs. Each species of Anopheles mosquito has its own preferred aquatic habitat; for example, some prefer small, shallow collections of fresh water, such as puddles and hoof prints, which are abundant during the rainy season in tropical countries.\n  \t\t\n  \t\tTransmission is more intense in places where the mosquito lifespan is longer (so that the parasite has time to complete its development inside the mosquito) and where it prefers to bite humans rather than other animals. The long lifespan and strong human-biting habit of the African vector species is the main reason why nearly 90% of the world's malaria cases are in Africa.\n  \t\t\n  \t\tTransmission also depends on climatic conditions that may affect the number and survival of mosquitoes, such as rainfall patterns, temperature and humidity. In many places, transmission is seasonal, with the peak during and just after the rainy season. Malaria epidemics can occur when climate and other conditions suddenly favour transmission in areas where people have little or no immunity to malaria. They can also occur when people with low immunity move into areas with intense malaria transmission, for instance to find work, or as refugees. \n  \t\t\n  \t\tHuman immunity is another important factor, especially among adults in areas of moderate or intense transmission conditions. Partial immunity is developed over years of exposure, and while it never provides complete protection, it does reduce the risk that malaria infection will cause severe disease. For this reason, most malaria deaths in Africa occur in young children, whereas in areas with less transmission and low immunity, all age groups are at risk.",
            "diagnosis": "\n  \t\t\n  \t\tEarly diagnosis and treatment of malaria reduces disease and prevents deaths. It also contributes to reducing malaria transmission. The best available treatment, particularly for P. falciparum malaria, is artemisinin-based combination therapy (ACT). \n  \t\t\n  \t\tWHO recommends that all cases of suspected malaria be confirmed using parasite-based diagnostic testing (either microscopy or rapid diagnostic test) before administering treatment. Results of parasitological confirmation can be available in 30 minutes or less. Treatment, solely on the basis of symptoms should only be considered when a parasitological diagnosis is not possible. More detailed recommendations are available in the \"WHO Guidelines for the treatment of malaria\", third edition, published in April 2015.",
            "treatment": "\n  \t\t\n  \t\tEarly diagnosis and treatment of malaria reduces disease and prevents deaths. It also contributes to reducing malaria transmission. The best available treatment, particularly for P. falciparum malaria, is artemisinin-based combination therapy (ACT). \n  \t\t\n  \t\tWHO recommends that all cases of suspected malaria be confirmed using parasite-based diagnostic testing (either microscopy or rapid diagnostic test) before administering treatment. Results of parasitological confirmation can be available in 30 minutes or less. Treatment, solely on the basis of symptoms should only be considered when a parasitological diagnosis is not possible. More detailed recommendations are available in the \"WHO Guidelines for the treatment of malaria\", third edition, published in April 2015.",
            "prevention": "\n  \t\t\n  \t\tVector control is the main way to prevent and reduce malaria transmission. If coverage of vector control interventions within a specific area is high enough, then a measure of protection will be conferred across the community. \n  \t\t\n  \t\tWHO recommends protection for all people at risk of malaria with effective malaria vector control. Two forms of vector control – insecticide-treated mosquito nets and indoor residual spraying – are effective in a wide range of circumstances. ",
            "more": "Source is http://www.who.int/entity/mediacentre/factsheets/fs094/en/index.html",
            "is_active": true
        }
    ])
    return info
}

export default DiseasesInfo
